name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install build-essential wget git -y
          sudo apt-get build-dep linux -y

      - name: 克隆内核仓库
        run: |
          git clone https://github.com/zabbly/linux.git
          cd linux
          git checkout linux-6.7

      - name: 配置内核
        run: |
          make defconfig

      - name: 编译内核
        run: |
          debian/rules do_tools=true binary-generic binary
          mkdir -p /packages && cp -f../*deb /packages/.

      - uses: actions/upload-artifact@v3
        with:
          name: linux_package
          path: /packages/
