name: Build Linux kernel 6.7 for Ubuntu 20.04

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ubuntu 20.04 environment
      uses: actions/setup-ubuntu@v1
      with:
        dist: focal

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev libssl-dev libelf-dev bison flex

    - name: Download kernel source code
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.7.tar.xz
        tar xf linux-6.7.tar.xz
        cd linux-6.7

    - name: Configure kernel
      run: |
        make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-
        make -j $(nproc) deb-pkg

    - name: Upload compiled files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-compiled
        path: linux-6.7/*.deb

    - name: Upload kernel config as artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel-config
        path: linux-6.7/.config
